matrix:
  include:
  - name: "GIFT COPR builds on Fedora 30 (Docker) with Python 3.7"
    env: FEDORA_VERSION="30"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "GIFT COPR builds on Fedora 31 (Docker) with Python 3.7"
    env: FEDORA_VERSION="31"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "GIFT PPA builds on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Source on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [TARGET="gitsource", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Source on MacOS 10.14 with Python 3.7 (tox)"
    env: [TARGET="gitsource", TOXENV="py37"]
    os: osx
    osx_image: xcode10
    language: generic
  - name: "Pylint on Ubuntu Bionic (18.04) with Python 3.6"
    env: [TARGET="pylint3", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Docker Hub builds on Ubuntu Xenial (16.04)"
    env: TARGET="dockerhub"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    services:
    - docker
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 45 ./config/travis/runtests.sh
